[virtualenvs]
in-project = true

[tool.poetry.dependencies]
urllib3 = ">=2.2.2,<3.0.0"
jinja2 = ">=3.1.4,<3.2"
black = ">=24.3.0,<25.0.0"
idna = ">=3.7,<3.8"
pydantic = ">=1.10.13,<1.11.0"
requests = ">=2.32.3,<2.33.0"
certifi = ">=2024.07.04,<2025.0.0"
zipp = ">=3.19.1,<3.20.0"
setuptools = ">=70.0.0,<71.0.0"
