# https://github.com/git-chglog/git-chglog
bin: git
style: "github"
template: "CHANGELOG.tpl.md"

info:
  title: "Changelog"
  repository_url: "https://github.com/getjavelin/javelin-python"

options:
  tag_filter_pattern: "^v"
  sort: "semver"

  commits:
    filters:
      Type:
        - feat
        - fix
        - devops
    sort_by: "Scope"

  commit_groups:
    group_by: "Type"
    sort_by: "Title"
    title_order:
      - feat
      - fix
      - devops
    title_maps:
      feat: "Features"
      fix: "Bug Fixes"
      devops: "DevOps"

  header:
    pattern: "^(\\w*)(\\(.+\\))?: (.+)$"
    pattern_maps:
      - Type
      - Scope
      - Subject

  notes:
    keywords:
      - BREAKING CHANGE