name: CICD Trivy Scan - Javelin Python

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "CHANGELOG.md"

jobs:
  reusable-workflow:
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'read'
      security-events: 'write'
    uses: getjavelin/javelin-workflow/.github/workflows/workflow-trivy-scan.yml@main
    secrets:
      DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}