name: PR Issue Status - Javelin Python

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  reusable-workflow:
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
      repository-projects: 'write'
    uses: getjavelin/javelin-workflow/.github/workflows/workflow-pr-issues-status.yml@main
    secrets:
      DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
      DEVOPS_GITHUB_TOKEN_CLASSIC: ${{ secrets.DEVOPS_GITHUB_TOKEN_CLASSIC }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}